---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flask-helm-flux
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/saiprakash07/flask-helm-flux

